# Limpieza de datos

La mayoría de la gente piensa que ser científico de datos significa estar corriendo modelos avanzados de Machine Learning todo el tiempo. La realidad es muy distinta:

![Tiempo de un científico de datos](./img/datascientist_time.jpeg)

La gran mayoría del tiempo se va **limpiando y organizando** los datos con los que queremos trabajar.

Los científicos de datos utilizamos herramientas como Pandas, Numpy, Matplotlib y Seaborn para limpiar los datos con los que queremos hacer algo.

## ETL

Un tipo de tarea que realizamos con gran frecuencia los científicos de datos son los **ETL**.

![Proceso de ETL](./img/etl.png)

ETL es un acrónimo que significa Extract, Transform, Load. Es un proceso que se utiliza para extraer datos de una fuente, transformarlos en un formato que sea adecuado para el análisis y cargarlos en una base de datos o algún otro sistema de almacenamiento.

## Ejemplo práctico

Los datos que usaremos para esta limpieza y nuestro siguiente análisis son datos de incidencia delictiva en nuestro país.

La iniciativa de datos abiertos del gobierno de México nos proporciona datos de incidencia delictiva desde 2015 hasta la fecha. Los datos se actualizan todos los meses y se pueden descargar desde el siguiente enlace: https://www.gob.mx/sesnsp/acciones-y-programas/datos-abiertos-de-incidencia-delictiva

---

Como podemos ver en el portal, se proporcionan los datos tanto a nivel estatal como a nivel municipal. En este caso, utilizaremos los datos a nivel estatal.

Descarguemos los datos y guardemos el archivo CSV en la carpeta data con el nombre `datos_delitos.csv`.

---

Ahora leamos el archivo CSV y veamos cómo se ven los datos.

Primero que nada, importemos pandas

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('data/datos_delitos.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 1: invalid continuation byte

Aquí tenemos un error muy común que suele ocurrir cuando un archivo se guarda en una computadora con cierto "encoding". 

Un encoding es una tabla que relaciona un número con un carácter. Por ejemplo, en la tabla ASCII, el número 65 corresponde a la letra "A".

Si el archivo que estamos leyendo fue guardado con un encoding distinto al que pandas espera, nos arrojará un error. 

Para solucionar esto, podemos utilizar el parámetro `encoding` de la función `pd.read_csv()` y especificar el encoding correcto.

¿Pero cómo sabemos con qué encoding cuenta el archivo?

La realidad es que la gran mayoría de los archivos los encontrarán en encoding utf-8 y Pandas no va a dar ningún error. Aquí estamos teniendo este problema porque la computadora que utilizan para generar este archivo uso un encoding diferente a utf-8.

En México, por lo general, si un archivo no está en utf-8, lo más seguro es que esté en `ISO-8859-1` o `latin1`.

Intentemos cargar el archivo especificando el encoding `ISO-8859-1`.

In [ ]:
df = pd.read_csv('data/datos_delitos.csv', encoding='ISO-8859-1')
df.head()

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0.0,1.0,2.0,0.0,0.0,0.0
3,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2,0,0,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0,0,0,0,1,0,0.0,0.0,0.0,0.0,0.0,0.0

Y vemos que ya podemos leer correctamente el archivo.


¿Existe alguna forma de verificar el encoding de un archivo sin tener que estar adivinando?

ChatGTP generó el siguiente código:

In [ ]:
import chardet

def detect_encoding(file_path):
    with open(file_path, 'rb') as f:
        rawdata = f.read()
    result = chardet.detect(rawdata)
    return result

file_path = './data/datos_delitos.csv'
encoding_info = detect_encoding(file_path)
print(f"Detected encoding: {encoding_info['encoding']}")

Detected encoding: ISO-8859-1

Sigamos...

In [ ]:
df.tail(3)

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
31357,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,20,22,34,35,34,37,NaN,NaN,NaN,NaN,NaN,NaN
31358,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Electorales,Electorales,Electorales,0,1,0,11,31,23,NaN,NaN,NaN,NaN,NaN,NaN
31359,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Otros delitos del Fuero Común,Otros delitos del Fuero Común,Otros delitos del Fuero Común,151,183,174,199,208,177,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31360 entries, 0 to 31359
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     31360 non-null  int64
 1   Clave_Ent               31360 non-null  int64
 2   Entidad                 31360 non-null  object
 3   Bien jurídico afectado  31360 non-null  object
 4   Tipo de delito          31360 non-null  object
 5   Subtipo de delito       31360 non-null  object
 6   Modalidad               31360 non-null  object
 7   Enero                   31360 non-null  int64
 8   Febrero                 31360 non-null  int64
 9   Marzo                   31360 non-null  int64
 10  Abril                   31360 non-null  int64
 11  Mayo                    31360 non-null  int64
 12  Junio                   31360 non-null  int64
 13  Julio                   28224 non-null  float64
 14  Agosto                  28224 non-null  float64
 15  Septiembre              28224 non-null  float64
 16  Octubre                 28224 non-null  float64
 17  Noviembre               28224 non-null  float64
 18  Diciembre               28224 non-null  float64
dtypes: float64(6), int64(8), object(5)
memory usage: 4.5+ MB

Bien. Están muy bien los datos. Sin embargo, tenemos un problema con el que es muy común encontrarnos. 

Resulta que el formato en el que está el archivo es fácil entender por seres humanos:


```markdown
| Año      | Entidad  | Enero    | Febrero  | Mes X    |
|----------|----------|----------|----------|----------|
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
```

Vemos que tenemos los meses como encabezados. Es decir, el archivo está tratando cada mes como si fuera una variable. 

Nosotros como científicos de datos estamos más interesados en conjuntos de datos que no estén en este formato de "resumen" o "tabla dinámica". Para nosotros, lo ideal sería que cada mes fuera simplemente una observación más en nuestro conjunto de datos. Es decir, queremos transformar la tabla de arriba en:

```markdown
| Año      | Entidad  | Mes        |
|----------|----------|------------|
|   ...    |   ...    |   Enero    |
|   ...    |   ...    |   Febrero  |
|   ...    |   ...    |   Marzo    |
|   ...    |   ...    |   Abril    |
|   ...    |   ...    |   Mes X    |
```

A este tipo de formato le llamos "formato largo de datos".

Haremos las siguientes limpiezas:
* Transformar los nombres de las columnas para que no tengan caracteres especiales y estén siempre en minúsculas
* Convertir el dataset a un formato de datos "largo"

In [ ]:
for col in df.columns:
    print(col)

Año
Clave_Ent
Entidad
Bien jurídico afectado
Tipo de delito
Subtipo de delito
Modalidad
Enero
Febrero
Marzo
Abril
Mayo
Junio
Julio
Agosto
Septiembre
Octubre
Noviembre
Diciembre

In [ ]:
len(df.columns)

19

### Limpiar nombres de columnas

In [ ]:
def limpiar_columnas(df):
    columnas_limpias = []
    for col in df.columns:
        # convertir a minusculas, reemplazar espacios por guiones bajos y eliminar caracteres especiales
        col = col.lower().replace(" ", "_").replace("ñ", "ni").replace(".", "").replace("á", "a").replace("é", "e").replace("í","i").replace("ó", "o").replace("ú", "u")
        columnas_limpias.append(col)
    
    df.columns = columnas_limpias
    
    return df

In [ ]:
df.head(2)

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0

In [ ]:
df = limpiar_columnas(df)

In [ ]:
df.head(3)

,anio,clave_ent,entidad,bien_juridico_afectado,tipo_de_delito,subtipo_de_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0.0,1.0,2.0,0.0,0.0,0.0

Muy bien. Ahora lo que queremos hacer es quitar algunas columnas. Nos interesan nada más las siguientes:

In [ ]:
df[['anio', 'entidad']]

       anio         entidad
0      2015  Aguascalientes
1      2015  Aguascalientes
2      2015  Aguascalientes
3      2015  Aguascalientes
4      2015  Aguascalientes
...     ...             ...
31355  2024       Zacatecas
31356  2024       Zacatecas
31357  2024       Zacatecas
31358  2024       Zacatecas
31359  2024       Zacatecas

[31360 rows x 2 columns]

In [ ]:
df = df[['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'subtipo_de_delito', 'modalidad','enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']]
df.head(2)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0

### Formato largo de datos

Ahora, usaremos el método `melt` para convertir las columnas a observaciones.

Queremos convervar las coumnas:
* anio
* clave_ent
* entidad
* tipo_de_delito
* subtipo_de_delito
* modalidad

El resto de las columnas las vamos a juntar en una nueva columna llamada "nombre_mes" y sus valores los vamos a sumar en otra llamada "frecuencia"

In [ ]:
print("Shape ", df.shape)

Shape  (31360, 18)

In [ ]:
datos_long = df.melt(id_vars=['anio', 'clave_ent', 'entidad','tipo_de_delito', 'subtipo_de_delito', 'modalidad'], var_name='nombre_mes', value_name='frecuencia')

In [ ]:
print("Shape: ", datos_long.shape)

Shape:  (376320, 8)

In [ ]:
datos_long.head(5)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,modalidad,nombre_mes,frecuencia
0,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma de fuego,enero,3.0
1,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma blanca,enero,1.0
2,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con otro elemento,enero,0.0
3,2015,1,Aguascalientes,Homicidio,Homicidio doloso,No especificado,enero,2.0
4,2015,1,Aguascalientes,Homicidio,Homicidio culposo,Con arma de fuego,enero,0.0

In [ ]:
datos_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376320 entries, 0 to 376319
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   anio               376320 non-null  int64
 1   clave_ent          376320 non-null  int64
 2   entidad            376320 non-null  object
 3   tipo_de_delito     376320 non-null  object
 4   subtipo_de_delito  376320 non-null  object
 5   modalidad          376320 non-null  object
 6   nombre_mes         376320 non-null  object
 7   frecuencia         357504 non-null  float64
dtypes: float64(1), int64(2), object(5)
memory usage: 23.0+ MB

Supongamos que para este análisis, no nos importan los niveles subtipo de delito y modalidad. O sea, no queremos tener la distinción entre homicidios dolosos y culposos (sé que son bastante diferentes, pero simplifiquemos nuestro ejemplo).

Vamos a agrupar nuestro dataframe por anio, clave_ent, entidad, tipo_de_delito y nombre_mes. Esto hará que todos los tipos de homicidios se sumen al tipo "homicidio" o todos los tipos de robo de vehículo (con o sin violencia) se sumen a "robo de vehículo".

In [ ]:
datos_long = datos_long.groupby(['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'nombre_mes'])['frecuencia'].sum().reset_index()

In [ ]:
datos_long[datos_long.tipo_de_delito == 'Robo'].sample(15)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia
52226,2018,13,Hidalgo,Robo,diciembre,1140.0
69029,2019,16,Michoacán de Ocampo,Robo,julio,1386.0
127593,2023,10,Durango,Robo,noviembre,275.0
2786,2015,6,Colima,Robo,diciembre,313.0
123273,2023,1,Aguascalientes,Robo,noviembre,840.0
132864,2023,21,Puebla,Robo,abril,2504.0
52233,2018,13,Hidalgo,Robo,noviembre,1425.0
53674,2018,16,Michoacán de Ocampo,Robo,octubre,1639.0
54634,2018,18,Nayarit,Robo,octubre,78.0
63265,2019,4,Campeche,Robo,agosto,102.0
4233,2015,9,Ciudad de México,Robo,noviembre,6320.0
62784,2019,3,Baja California Sur,Robo,abril,719.0
133346,2023,22,Querétaro,Robo,diciembre,2050.0
80555,2020,8,Chihuahua,Robo,septiembre,1075.0
120870,2022,28,Tamaulipas,Robo,junio,669.0

Mostremos todos los estados y su respectiva clave

In [ ]:
datos_long[['clave_ent', 'entidad']].drop_duplicates().sort_values('entidad')

       clave_ent                          entidad
0              1                   Aguascalientes
480            2                  Baja California
960            3              Baja California Sur
1440           4                         Campeche
2880           7                          Chiapas
3360           8                        Chihuahua
3840           9                 Ciudad de México
1920           5             Coahuila de Zaragoza
2400           6                           Colima
4320          10                          Durango
4800          11                       Guanajuato
5280          12                         Guerrero
5760          13                          Hidalgo
6240          14                          Jalisco
7200          16              Michoacán de Ocampo
7680          17                          Morelos
6720          15                           México
8160          18                          Nayarit
8640          19                       Nuevo León
9120          20                           Oaxaca
9600          21                           Puebla
10080         22                        Querétaro
10560         23                     Quintana Roo
11040         24                  San Luis Potosí
11520         25                          Sinaloa
12000         26                           Sonora
12480         27                          Tabasco
12960         28                       Tamaulipas
13440         29                         Tlaxcala
13920         30  Veracruz de Ignacio de la Llave
14400         31                          Yucatán
14880         32                        Zacatecas

Ahora Veamos todos los datos de delitos de una entidad en específico. Por ejemplo, Nuevo león

In [ ]:
datos_long[datos_long['clave_ent'] == 19].sample(15)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia
39820,2017,19,Nuevo León,Violencia de género en todas sus modalidades d...,febrero,0.0
70186,2019,19,Nuevo León,Daño a la propiedad,octubre,612.0
131625,2023,19,Nuevo León,Daño a la propiedad,noviembre,605.0
8706,2015,19,Nuevo León,Amenazas,junio,323.0
147141,2024,19,Nuevo León,Incumplimiento de obligaciones de asistencia f...,noviembre,0.0
39476,2017,19,Nuevo León,Delitos cometidos por servidores públicos,mayo,179.0
116161,2022,19,Nuevo León,Aborto,agosto,11.0
131842,2023,19,Nuevo León,Otros delitos contra la sociedad,octubre,1.0
8772,2015,19,Nuevo León,Electorales,abril,1.0
39676,2017,19,Nuevo León,Otros delitos contra la sociedad,febrero,0.0
146922,2024,19,Nuevo León,Acoso sexual,junio,47.0
85510,2020,19,Nuevo León,Amenazas,octubre,431.0
85788,2020,19,Nuevo León,Otros delitos que atentan contra la libertad y...,abril,48.0
70344,2019,19,Nuevo León,Lesiones,abril,466.0
147132,2024,19,Nuevo León,Incumplimiento de obligaciones de asistencia f...,abril,72.0

In [ ]:
datos_long[(datos_long['clave_ent'] > 19) &  (datos_long['clave_ent'] < 24) & (datos_long['tipo_de_delito'] == 'Homicidio')].sample(15)

        anio  clave_ent       entidad tipo_de_delito nombre_mes  frecuencia
149026  2024         23  Quintana Roo      Homicidio    octubre         0.0
86618   2020         21        Puebla      Homicidio  diciembre       110.0
102456  2021         22     Querétaro      Homicidio      abril        43.0
41021   2017         22     Querétaro      Homicidio      julio        34.0
10782   2015         23  Quintana Roo      Homicidio      junio        46.0
149021  2024         23  Quintana Roo      Homicidio      julio         0.0
25664   2016         22     Querétaro      Homicidio       mayo        47.0
102940  2021         23  Quintana Roo      Homicidio    febrero       117.0
25185   2016         21        Puebla      Homicidio  noviembre        65.0
26146   2016         23  Quintana Roo      Homicidio    octubre        33.0
9340    2015         20        Oaxaca      Homicidio    febrero       105.0
26145   2016         23  Quintana Roo      Homicidio  noviembre        30.0
10305   2015         22     Querétaro      Homicidio  noviembre        45.0
41017   2017         22     Querétaro      Homicidio     agosto        47.0
25661   2016         22     Querétaro      Homicidio      julio        40.0

### Valores de fechas

Finalmente, queremos tener una columna "fecha". Actualmente tenemos el año y el nombre del mes, pero no tenemos como tal una columna que tenga un tipo de dato fecha. Eso hace que filtrar por fecha sea complicado.

Por ejemplo, si queremos conocer todos los homicidios de Oaxaca en enero 2024, haríamos lo siguiente:

In [ ]:
datos_long[
    (datos_long['clave_ent'] == 20) &
    (datos_long['tipo_de_delito'] == 'Homicidio') &
    (datos_long['anio'] == 2024) &
    (datos_long['nombre_mes'] == 'enero') 
]

        anio  clave_ent entidad tipo_de_delito nombre_mes  frecuencia
147579  2024         20  Oaxaca      Homicidio      enero       157.0

Creemos una columna de fecha. 

Primero tenemos que convertir el nombre de mes a un número, en donde 1 es enero, 2 febrero, etc.

In [ ]:
datos_long.sample(2)

        anio  clave_ent  entidad     tipo_de_delito  nombre_mes  frecuencia
119315  2022         25  Sinaloa           Lesiones  septiembre       352.0
125433  2023          6   Colima  Evasión de presos   noviembre         0.0

In [ ]:
datos_long["nueva_columna"] = "dato vacío"
datos_long.sample(6)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna
92880,2021,2,Baja California,Incesto,abril,0.0,dato vacío
56512,2018,22,Querétaro,Otros delitos que atentan contra la libertad y...,febrero,7.0,dato vacío
86915,2020,22,Querétaro,Abuso sexual,septiembre,51.0,dato vacío
83254,2020,14,Jalisco,Fraude,octubre,748.0,dato vacío
26980,2016,25,Sinaloa,Daño a la propiedad,febrero,164.0,dato vacío
89180,2020,26,Sonora,Rapto,mayo,0.0,dato vacío

In [ ]:
# Diccionario de ayuda para convertir
meses = {
    "enero": 1,
    "febrero": 2,
    "marzo": 3,
    "abril": 4,
    "mayo": 5,
    "junio": 6,
    "julio": 7,
    "agosto": 8,
    "septiembre": 9,
    "octubre": 10,
    "noviembre": 11,
    "diciembre": 12
}

datos_long['mes'] = datos_long['nombre_mes'].map(meses)
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes
126983,2023,9,Ciudad de México,Incumplimiento de obligaciones de asistencia f...,septiembre,95.0,dato vacío,9
52422,2018,14,Jalisco,Daño a la propiedad,junio,611.0,dato vacío,6
28245,2016,27,Tabasco,Secuestro,noviembre,10.0,dato vacío,11
130423,2023,16,Michoacán de Ocampo,Otros delitos que atentan contra la libertad p...,marzo,25.0,dato vacío,3
32630,2017,4,Campeche,Violencia familiar,diciembre,4.0,dato vacío,12

In [ ]:
datos_long["frecuencia_mas_10"] = datos_long["frecuencia"] + 10
datos_long.sample(5)#sirve para ver que se haya creado la nueva columna correctamente

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10
124143,2023,3,Baja California Sur,Otros delitos contra la familia,enero,22.0,dato vacío,1,32.0
62395,2019,2,Baja California,Violencia familiar,marzo,769.0,dato vacío,3,779.0
106424,2021,30,Veracruz de Ignacio de la Llave,Otros delitos que atentan contra la libertad p...,mayo,52.0,dato vacío,5,62.0
71449,2019,21,Puebla,Trata de personas,agosto,1.0,dato vacío,8,11.0
83814,2020,15,México,Otros delitos contra el patrimonio,junio,15.0,dato vacío,6,25.0

In [ ]:
datos_long["anio_mes"] = datos_long["anio"].astype(str) + datos_long["mes"].astype(str)
datos_long.sample(6)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10,anio_mes
32229,2017,4,Campeche,Amenazas,noviembre,3.0,dato vacío,11,13.0,201711
127549,2023,10,Durango,Otros delitos que atentan contra la libertad y...,agosto,15.0,dato vacío,8,25.0,20238
20910,2016,12,Guerrero,Lesiones,junio,252.0,dato vacío,6,262.0,20166
21759,2016,14,Jalisco,Extorsión,enero,52.0,dato vacío,1,62.0,20161
146587,2024,18,Nayarit,Falsificación,marzo,1.0,dato vacío,3,11.0,20243
144986,2024,15,México,Abuso sexual,diciembre,0.0,dato vacío,12,10.0,202412

In [ ]:
# yyyy-mm-dd, yy-mm-dd, yymmdd, yyyy/dd/mm

In [ ]:
# Agregamos la columna de fecha juntando el año y el mes
datos_long['fecha'] = pd.to_datetime(datos_long['anio'].astype(str) + datos_long['mes'].astype(str), format='%Y%m')
datos_long.sample(5)

NameError: name 'datos_long' is not defined

In [ ]:
# Eliminamos las columnas que ya no necesitamos
datos_long = datos_long.drop(columns=['nueva_columna'])
datos_long.sample(5)

NameError: name 'datos_long' is not defined

Veamos los homicidios en oaxaca de enero 2024 a la fecha

In [ ]:
datos_long[
    (datos_long.tipo_de_delito == "Homicidio") &
    (datos_long.clave_ent == 20) &
    (datos_long.fecha >= '2024-01-01')
].sort_values('fecha')

NameError: name 'datos_long' is not defined

In [ ]:
datos_finales = datos_long[['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'nombre_mes', 'fecha', 'frecuencia']]
datos_finales.head(2)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,fecha,frecuencia
0,2015,1,Aguascalientes,Aborto,abril,2015-04-01,0.0
1,2015,1,Aguascalientes,Aborto,agosto,2015-08-01,0.0

Ya que tenemos muestros datos bien estructurados, los podemos guardar en nuestra computadora. Los guardaremos con el nombre "delitos.csv"

In [ ]:
datos_finales.to_csv('data/delitos.csv', index=False)